### ISSUE TITLE
mutton_demo build failed

### ISSUE THREAD

**Issue by tgruben** [project-z/mutton#1]
I have successfully built the libmutton from the query_parser branch and the unit tests work.  The mutton_demo is failling to build on OSX. I wasn't sure if you where ready for feedback, just thought I would let you know the status from a noobs point of view.

mutton/src/naive_query_planner.hpp:144:26: error: no matching constructor for initialization of 'mtn::index_t'
            mtn::index_t index;

**Comment by mstump** [comment]
Just an FYI, this is still alpha at best, expect things to be broken.
